### ISSUE TITLE
viz_results.py issue

### ISSUE THREAD

**Issue by seanfw** [seanfw/margulies_circuit#2]
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /var/folders/bf/2p8n6f_15w5c30b4_nq12xqw0000gn/T/brian_debug_v8fjckuu.log  Additionally, you can also include a copy of the script that was run, available at: /var/folders/bf/2p8n6f_15w5c30b4_nq12xqw0000gn/T/brian_script_zvu0fe4u.py Thanks! [brian2]
Traceback (most recent call last):
  File "./main.py", line 119, in <module>
    plot_surfaces(pm['R'])
  File "/Users/seanfw/Dropbox/papers_in_progress/Margulies_surface_modelling/circuit/viz_results.py", line 14, in plot_surfaces
    c = config['SETUP']
  File "/Users/seanfw/miniconda2/envs/margulies_circuit/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'SETUP'

**Comment by margulies** [comment]
Here are new versions of the main.py and viz_results.py files:
https://www.dropbox.com/s/am7edmtttdaxuui/viz_results.py?dl=0
https://www.dropbox.com/s/do79kp4qgyrhf5o/main.py?dl=0

I've modified the viz functions so they take the config information directly from the main.py script. Let me know if that fixes the problem...

**Comment by seanfw** [comment]
Thanks!

I can get it to run now!

I had to remove 'circuits/' from all of the relative paths, and also comment out line  
190 of surf_plotting.py , which was throwing an error.
